/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlgorithmParameter from './AlgorithmParameter';

/**
 * The Algorithm model module.
 * @module model/Algorithm
 * @version 0.0.5
 */
class Algorithm {
    /**
     * Constructs a new <code>Algorithm</code>.
     * @alias module:model/Algorithm
     */
    constructor() { 
        
        Algorithm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Algorithm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Algorithm} obj Optional instance to populate.
     * @return {module:model/Algorithm} The populated <code>Algorithm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Algorithm();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('manifest')) {
                obj['manifest'] = ApiClient.convertToType(data['manifest'], 'String');
            }
            if (data.hasOwnProperty('cluster')) {
                obj['cluster'] = ApiClient.convertToType(data['cluster'], 'Number');
            }
            if (data.hasOwnProperty('files_per_job')) {
                obj['files_per_job'] = ApiClient.convertToType(data['files_per_job'], 'Number');
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], ['String']);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [AlgorithmParameter]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Algorithm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Algorithm</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['manifest'] && !(typeof data['manifest'] === 'string' || data['manifest'] instanceof String)) {
            throw new Error("Expected the field `manifest` to be a primitive type in the JSON string but got " + data['manifest']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['categories'])) {
            throw new Error("Expected the field `categories` to be an array in the JSON data but got " + data['categories']);
        }
        if (data['parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parameters'])) {
                throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
            }
            // validate the optional field `parameters` (array)
            for (const item of data['parameters']) {
                AlgorithmParameter.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Unique integer identifying the registered algorithm.
 * @member {Number} id
 */
Algorithm.prototype['id'] = undefined;

/**
 * Unique integer identifying the project associated with the algorithm.
 * @member {Number} project
 */
Algorithm.prototype['project'] = undefined;

/**
 * Unique name of the algorithm workflow.
 * @member {String} name
 */
Algorithm.prototype['name'] = undefined;

/**
 * Unique integer identifying the user registering the algorithm.
 * @member {Number} user
 */
Algorithm.prototype['user'] = undefined;

/**
 * Description of the algorithm.
 * @member {String} description
 */
Algorithm.prototype['description'] = undefined;

/**
 * Server URL to argo manifest file (.yaml)
 * @member {String} manifest
 */
Algorithm.prototype['manifest'] = undefined;

/**
 * Unique integer identifying the job cluster.
 * @member {Number} cluster
 */
Algorithm.prototype['cluster'] = undefined;

/**
 * Number of media files to be submitted to each workflow.
 * @member {Number} files_per_job
 */
Algorithm.prototype['files_per_job'] = undefined;

/**
 * List of categories the algorithm workflow belongs to
 * @member {Array.<String>} categories
 */
Algorithm.prototype['categories'] = undefined;

/**
 * List of algorithm workflow parameters
 * @member {Array.<module:model/AlgorithmParameter>} parameters
 */
Algorithm.prototype['parameters'] = undefined;






export default Algorithm;

