/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EncodeConfig from './EncodeConfig';
import S3StorageConfig from './S3StorageConfig';

/**
 * The ArchiveConfig model module.
 * @module model/ArchiveConfig
 * @version 0.0.5
 */
class ArchiveConfig {
    /**
     * Constructs a new <code>ArchiveConfig</code>.
     * Settings for archival video encode and storage. If not set, the raw video will be stored in Tator.
     * @alias module:model/ArchiveConfig
     * @param encode {module:model/EncodeConfig} 
     */
    constructor(encode) { 
        
        ArchiveConfig.initialize(this, encode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, encode) { 
        obj['encode'] = encode;
    }

    /**
     * Constructs a <code>ArchiveConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArchiveConfig} obj Optional instance to populate.
     * @return {module:model/ArchiveConfig} The populated <code>ArchiveConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArchiveConfig();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('encode')) {
                obj['encode'] = EncodeConfig.constructFromObject(data['encode']);
            }
            if (data.hasOwnProperty('s3_storage')) {
                obj['s3_storage'] = S3StorageConfig.constructFromObject(data['s3_storage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArchiveConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArchiveConfig</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ArchiveConfig.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `s3_storage`
        if (data['s3_storage']) { // data not null
          S3StorageConfig.validateJSON(data['s3_storage']);
        }

        return true;
    }


}

ArchiveConfig.RequiredProperties = ["encode"];

/**
 * Name of this archive config, used for retrieval in case of multiple archive configs.
 * @member {String} name
 */
ArchiveConfig.prototype['name'] = undefined;

/**
 * @member {module:model/EncodeConfig} encode
 */
ArchiveConfig.prototype['encode'] = undefined;

/**
 * @member {module:model/S3StorageConfig} s3_storage
 */
ArchiveConfig.prototype['s3_storage'] = undefined;






export default ArchiveConfig;

