/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AutocompleteService model module.
 * @module model/AutocompleteService
 * @version 0.0.5
 */
class AutocompleteService {
    /**
     * Constructs a new <code>AutocompleteService</code>.
     * @alias module:model/AutocompleteService
     */
    constructor() { 
        
        AutocompleteService.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AutocompleteService</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AutocompleteService} obj Optional instance to populate.
     * @return {module:model/AutocompleteService} The populated <code>AutocompleteService</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutocompleteService();

            if (data.hasOwnProperty('serviceUrl')) {
                obj['serviceUrl'] = ApiClient.convertToType(data['serviceUrl'], 'String');
            }
            if (data.hasOwnProperty('match_any')) {
                obj['match_any'] = ApiClient.convertToType(data['match_any'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AutocompleteService</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AutocompleteService</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['serviceUrl'] && !(typeof data['serviceUrl'] === 'string' || data['serviceUrl'] instanceof String)) {
            throw new Error("Expected the field `serviceUrl` to be a primitive type in the JSON string but got " + data['serviceUrl']);
        }

        return true;
    }


}



/**
 * URL of the autocomplete service.
 * @member {String} serviceUrl
 */
AutocompleteService.prototype['serviceUrl'] = undefined;

/**
 * If true, autocomplete will find leaves with any part of name matching the query. Otherwise only leaf names that start with the query are returned.
 * @member {Boolean} match_any
 * @default false
 */
AutocompleteService.prototype['match_any'] = false;






export default AutocompleteService;

