/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuxiliaryFileDefinition model module.
 * @module model/AuxiliaryFileDefinition
 * @version 0.0.5
 */
class AuxiliaryFileDefinition {
    /**
     * Constructs a new <code>AuxiliaryFileDefinition</code>.
     * @alias module:model/AuxiliaryFileDefinition
     * @param path {String} Relative URL to the file.
     */
    constructor(path) { 
        
        AuxiliaryFileDefinition.initialize(this, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, path) { 
        obj['path'] = path;
    }

    /**
     * Constructs a <code>AuxiliaryFileDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuxiliaryFileDefinition} obj Optional instance to populate.
     * @return {module:model/AuxiliaryFileDefinition} The populated <code>AuxiliaryFileDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuxiliaryFileDefinition();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('http_auth')) {
                obj['http_auth'] = ApiClient.convertToType(data['http_auth'], 'String');
            }
            if (data.hasOwnProperty('mime')) {
                obj['mime'] = ApiClient.convertToType(data['mime'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuxiliaryFileDefinition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuxiliaryFileDefinition</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuxiliaryFileDefinition.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['http_auth'] && !(typeof data['http_auth'] === 'string' || data['http_auth'] instanceof String)) {
            throw new Error("Expected the field `http_auth` to be a primitive type in the JSON string but got " + data['http_auth']);
        }
        // ensure the json data is a string
        if (data['mime'] && !(typeof data['mime'] === 'string' || data['mime'] instanceof String)) {
            throw new Error("Expected the field `mime` to be a primitive type in the JSON string but got " + data['mime']);
        }

        return true;
    }


}

AuxiliaryFileDefinition.RequiredProperties = ["path"];

/**
 * Name of the file.
 * @member {String} name
 */
AuxiliaryFileDefinition.prototype['name'] = undefined;

/**
 * Relative URL to the file.
 * @member {String} path
 */
AuxiliaryFileDefinition.prototype['path'] = undefined;

/**
 * File size in bytes.
 * @member {Number} size
 */
AuxiliaryFileDefinition.prototype['size'] = undefined;

/**
 * If supplied will use this instead of currently connected host, e.g. https://example.com
 * @member {String} host
 */
AuxiliaryFileDefinition.prototype['host'] = undefined;

/**
 * If specified will be used for HTTP authorization in request for media, i.e. \"bearer TOKEN\".
 * @member {String} http_auth
 */
AuxiliaryFileDefinition.prototype['http_auth'] = undefined;

/**
 * Example mime: \"text/csv\".
 * @member {String} mime
 */
AuxiliaryFileDefinition.prototype['mime'] = undefined;






export default AuxiliaryFileDefinition;

