/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DownloadInfoSpec model module.
 * @module model/DownloadInfoSpec
 * @version 0.0.5
 */
class DownloadInfoSpec {
    /**
     * Constructs a new <code>DownloadInfoSpec</code>.
     * @alias module:model/DownloadInfoSpec
     * @param keys {Array.<String>} Array of object keys for download info retrieval.
     */
    constructor(keys) { 
        
        DownloadInfoSpec.initialize(this, keys);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, keys) { 
        obj['keys'] = keys;
    }

    /**
     * Constructs a <code>DownloadInfoSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DownloadInfoSpec} obj Optional instance to populate.
     * @return {module:model/DownloadInfoSpec} The populated <code>DownloadInfoSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DownloadInfoSpec();

            if (data.hasOwnProperty('keys')) {
                obj['keys'] = ApiClient.convertToType(data['keys'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DownloadInfoSpec</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DownloadInfoSpec</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DownloadInfoSpec.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['keys'])) {
            throw new Error("Expected the field `keys` to be an array in the JSON data but got " + data['keys']);
        }

        return true;
    }


}

DownloadInfoSpec.RequiredProperties = ["keys"];

/**
 * Array of object keys for download info retrieval.
 * @member {Array.<String>} keys
 */
DownloadInfoSpec.prototype['keys'] = undefined;






export default DownloadInfoSpec;

