/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvitationSpec model module.
 * @module model/InvitationSpec
 * @version 0.0.5
 */
class InvitationSpec {
    /**
     * Constructs a new <code>InvitationSpec</code>.
     * @alias module:model/InvitationSpec
     * @param email {String} Email address of invitee.
     * @param permission {module:model/InvitationSpec.PermissionEnum} User permission level for the organization.
     */
    constructor(email, permission) { 
        
        InvitationSpec.initialize(this, email, permission);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, permission) { 
        obj['email'] = email;
        obj['permission'] = permission;
    }

    /**
     * Constructs a <code>InvitationSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvitationSpec} obj Optional instance to populate.
     * @return {module:model/InvitationSpec} The populated <code>InvitationSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvitationSpec();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InvitationSpec</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InvitationSpec</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InvitationSpec.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['permission'] && !(typeof data['permission'] === 'string' || data['permission'] instanceof String)) {
            throw new Error("Expected the field `permission` to be a primitive type in the JSON string but got " + data['permission']);
        }

        return true;
    }


}

InvitationSpec.RequiredProperties = ["email", "permission"];

/**
 * Email address of invitee.
 * @member {String} email
 */
InvitationSpec.prototype['email'] = undefined;

/**
 * User permission level for the organization.
 * @member {module:model/InvitationSpec.PermissionEnum} permission
 */
InvitationSpec.prototype['permission'] = undefined;





/**
 * Allowed values for the <code>permission</code> property.
 * @enum {String}
 * @readonly
 */
InvitationSpec['PermissionEnum'] = {

    /**
     * value: "Member"
     * @const
     */
    "Member": "Member",

    /**
     * value: "Admin"
     * @const
     */
    "Admin": "Admin"
};



export default InvitationSpec;

