/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeType from './AttributeType';

/**
 * The LeafTypeSpec model module.
 * @module model/LeafTypeSpec
 * @version 0.0.5
 */
class LeafTypeSpec {
    /**
     * Constructs a new <code>LeafTypeSpec</code>.
     * Leaf type spec.
     * @alias module:model/LeafTypeSpec
     */
    constructor() { 
        
        LeafTypeSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LeafTypeSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LeafTypeSpec} obj Optional instance to populate.
     * @return {module:model/LeafTypeSpec} The populated <code>LeafTypeSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeafTypeSpec();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('attribute_types')) {
                obj['attribute_types'] = ApiClient.convertToType(data['attribute_types'], [AttributeType]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LeafTypeSpec</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LeafTypeSpec</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['attribute_types']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attribute_types'])) {
                throw new Error("Expected the field `attribute_types` to be an array in the JSON data but got " + data['attribute_types']);
            }
            // validate the optional field `attribute_types` (array)
            for (const item of data['attribute_types']) {
                AttributeType.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Name of the leaf type.
 * @member {String} name
 */
LeafTypeSpec.prototype['name'] = undefined;

/**
 * Description of the leaf type.
 * @member {String} description
 * @default ''
 */
LeafTypeSpec.prototype['description'] = '';

/**
 * Attribute type definitions.
 * @member {Array.<module:model/AttributeType>} attribute_types
 */
LeafTypeSpec.prototype['attribute_types'] = undefined;






export default LeafTypeSpec;

