/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeValue from './AttributeValue';

/**
 * The LocalizationUpdate model module.
 * @module model/LocalizationUpdate
 * @version 0.0.5
 */
class LocalizationUpdate {
    /**
     * Constructs a new <code>LocalizationUpdate</code>.
     * @alias module:model/LocalizationUpdate
     */
    constructor() { 
        
        LocalizationUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LocalizationUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocalizationUpdate} obj Optional instance to populate.
     * @return {module:model/LocalizationUpdate} The populated <code>LocalizationUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocalizationUpdate();

            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('u')) {
                obj['u'] = ApiClient.convertToType(data['u'], 'Number');
            }
            if (data.hasOwnProperty('v')) {
                obj['v'] = ApiClient.convertToType(data['v'], 'Number');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], [['Number']]);
            }
            if (data.hasOwnProperty('frame')) {
                obj['frame'] = ApiClient.convertToType(data['frame'], 'Number');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'Number');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': AttributeValue});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LocalizationUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LocalizationUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['points'])) {
            throw new Error("Expected the field `points` to be an array in the JSON data but got " + data['points']);
        }

        return true;
    }


}



/**
 * Normalized horizontal position of left edge of bounding box for `box` localization types, start of line for `line` localization types, or position of dot for `dot` localization types.
 * @member {Number} x
 */
LocalizationUpdate.prototype['x'] = undefined;

/**
 * Normalized vertical position of top edge of bounding box for `box` localization types, start of line for `line` localization types, or position of dot for `dot` localization types.
 * @member {Number} y
 */
LocalizationUpdate.prototype['y'] = undefined;

/**
 * Normalized width of bounding box for `box` localization types.
 * @member {Number} width
 */
LocalizationUpdate.prototype['width'] = undefined;

/**
 * Normalized height of bounding box for `box` localization types.
 * @member {Number} height
 */
LocalizationUpdate.prototype['height'] = undefined;

/**
 * Horizontal vector component for `line` localization types.
 * @member {Number} u
 */
LocalizationUpdate.prototype['u'] = undefined;

/**
 * Vertical vector component for `line` localization types.
 * @member {Number} v
 */
LocalizationUpdate.prototype['v'] = undefined;

/**
 * List of normalized [x, y] pairs for `poly` localization types.
 * @member {Array.<Array.<Number>>} points
 */
LocalizationUpdate.prototype['points'] = undefined;

/**
 * Frame number of this localization if it is in a video.
 * @member {Number} frame
 */
LocalizationUpdate.prototype['frame'] = undefined;

/**
 * If a clone, the pk of the parent.
 * @member {Number} parent
 */
LocalizationUpdate.prototype['parent'] = undefined;

/**
 * Object containing attribute values.
 * @member {Object.<String, module:model/AttributeValue>} attributes
 */
LocalizationUpdate.prototype['attributes'] = undefined;






export default LocalizationUpdate;

