/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MediaStats model module.
 * @module model/MediaStats
 * @version 0.0.5
 */
class MediaStats {
    /**
     * Constructs a new <code>MediaStats</code>.
     * @alias module:model/MediaStats
     */
    constructor() { 
        
        MediaStats.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaStats} obj Optional instance to populate.
     * @return {module:model/MediaStats} The populated <code>MediaStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaStats();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('download_size')) {
                obj['download_size'] = ApiClient.convertToType(data['download_size'], 'Number');
            }
            if (data.hasOwnProperty('total_size')) {
                obj['total_size'] = ApiClient.convertToType(data['total_size'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MediaStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MediaStats</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} count
 */
MediaStats.prototype['count'] = undefined;

/**
 * @member {Number} download_size
 */
MediaStats.prototype['download_size'] = undefined;

/**
 * @member {Number} total_size
 */
MediaStats.prototype['total_size'] = undefined;

/**
 * @member {Number} duration
 */
MediaStats.prototype['duration'] = undefined;






export default MediaStats;

